## Skeleton page for generating Igor test procedure files
<%namespace file="TEST.mako" import="MAIN" />
#pragma rtGlobals=1

#include "IgorUnit"

// This file is automatically generated from test files by the IgorUnit package
<%block name="IgorUnit">${next.body()}</%block>
${MAIN()}
